// 120+ viral YouTube title formats. [X], [Y], [Z] are open-ended blanks
// players fill in after choosing a persona.
const FORMATS = [
  'I Tried Living Like [X] for [Y] Days',
  'I Spent [X] Hours With [Y]',
  'I Let [X] Control My Life',
  'I Survived [X] Without [Y]',
  'I Built [X] in [Y] Days',
  'I Bought the Cheapest [X]',
  'I Tested [X] So You Don\'t Have To',
  'I Followed [X]\'s Routine for a Week',
  'I Tried Every [X] in [Y]',
  'I Let AI Decide [X]',
  'I Became [X] for 24 Hours',
  'I Hired [X] to Help Me [Y]',
  'I Challenged [X] to [Y]',
  'I Found the Worst [X] on the Internet',
  'I Made [X] Using Only [Y]',
  'I Tried the World\'s Most [X]',
  'I Used [X] Every Day for 30 Days',
  'I Recreated [X] From Scratch',
  'I Tested Viral [X] Hacks',
  'I Tried [X] With Zero Experience',

  // 100 more
  'Last to Leave [X] Wins $10,000',
  '100 [X] vs 1 [Y]',
  'Giving [X] to Strangers Until One Says No',
  'I Switched Lives With [X] for a Day',
  'I Spent 24 Hours in [X]',
  'I Spent 24 Hours Buried Alive With [X]',
  'I Gave My Mom Control of [X]',
  'I Bought Everything My [X] Touched',
  'I Tried [X] Until I Couldn\'t Move',
  'I Trained Like [X] for 30 Days',
  'I Ate Like [X] for a Week',
  'I Slept Like [X] for 7 Nights',
  'I Dressed Like [X] for a Month',
  'Ranking Every [X] From Worst to Best',
  'Tier Listing [X] Until I Cry',
  'Rating [X] Out of 10',
  'Reacting to [X] for the First Time',
  'Reacting to My Old [X]',
  'Reading Hate Comments About [X]',
  'I Read Every Comment on My [X] Video',
  'Ranking [X]\'s Most Viral Moments',
  'The Untold Truth About [X]',
  'Why Everyone Is Wrong About [X]',
  'The Dark Side of [X]',
  'The Secret Life of [X]',
  'Inside [X]\'s Secret Bunker',
  'I Snuck Into [X]',
  'I Broke Into [X] (Not Clickbait)',
  'Exposing [X] Once and For All',
  'Confronting [X] After 10 Years',
  'Meeting [X] in Real Life',
  'My First Time [X]',
  'My Last Day of [X]',
  'The Day I Became [X]',
  'How [X] Changed My Life Forever',
  'How I Made $1,000,000 From [X]',
  'How I Lost Everything Because of [X]',
  'I Quit My Job to [X]',
  'I Moved to [X] for a Month',
  'I Lived in [X] for a Week',
  'I Slept in [X] Overnight',
  'I Stayed Up 72 Hours Doing [X]',
  'Speedrunning [X] in Real Life',
  'Can I Beat [X] in 24 Hours?',
  'Can I Survive [X]?',
  'Can You Guess [X]?',
  'Guess the [X] or Get Slimed',
  'Telling My [X] I\'m Quitting',
  'Surprising My [X] With [Y]',
  'Surprising [X] With Their Dream [Y]',
  'I Gave [X] a $100,000 Makeover',
  'I Gave a Stranger [X] (Emotional)',
  'Buying My [X] Everything They Point At',
  'I Took [X] on the World\'s Worst Date',
  'I Pranked [X] With [Y]',
  'I Went Undercover as [X]',
  'Catfishing [X] for 24 Hours',
  'I Only Ate [X] for a Week',
  'I Only Drank [X] for 3 Days',
  'I Only Spoke in [X] for 24 Hours',
  'I Was Trapped With [X] for 100 Hours',
  'Stuck on a Deserted Island With [X]',
  'Surviving the Wilderness as [X]',
  'Beating [X] Using Only [Y]',
  'Defeating [X] With One Hand',
  'Can a [X] Defeat a [Y]?',
  'Testing Every [X] So You Don\'t Have To',
  'Blind Taste Testing [X]',
  'Cheap vs Expensive [X]',
  '$1 vs $1,000,000 [X]',
  '$1 [X] vs $10,000 [X]',
  'Budget [X] vs Luxury [X]',
  'Fake [X] vs Real [X]',
  'Pros Review [X]',
  'Experts Rank [X]',
  'I Asked [X] to Rank [Y]',
  'What [X] Looks Like Behind the Scenes',
  'A Day in the Life of [X]',
  'A Week in the Life of [X]',
  '24 Hours in [X]\'s Shoes',
  '[X] Tries [Y] for the First Time',
  '[X] Reacts to [Y]',
  '[X] Teaches Me How to [Y]',
  'I Asked [X] the Hardest Question',
  'The Truth About What Happened to [X]',
  'Where Did [X] Go? (Investigation)',
  'Finding [X] After 20 Years',
  'I Found [X]\'s Secret Twin',
  'I Cloned [X]',
  'I Raised [X] From Scratch',
  'Training [X] to Beat Me',
  'Teaching My [X] to [Y]',
  '[X] but It\'s Actually Terrifying',
  '[X] but Everyone Lies',
  '[X] but the Floor Is Lava',
  'When [X] Goes Horribly Wrong',
  '[X] Gone Wrong (Gone Sexual) (Cops Called)',
  'Don\'t Click This Video About [X]',
  'This [X] Shouldn\'t Exist',
  'The Most Illegal [X] Ever Made',
  'The World\'s Smallest [X]',
  'The World\'s Biggest [X] Challenge',
  'Shortest vs Tallest [X]',
  'Oldest vs Youngest [X]',
  'Rich [X] vs Broke [X]',
  'Nerd [X] vs Jock [X]',
  'Boys vs Girls [X]',
  'Kid vs Adult [X]',
  'AI vs Human [X]',
  'Will This [X] Actually Work?',
  '5 [X] Hacks That Actually Work',
  '10 [X] Myths Busted',
  '7 Reasons You\'re Doing [X] Wrong',
  'Why I Stopped Doing [X]',
  'Why Nobody Talks About [X] Anymore',
  'The End of [X] As We Know It',
  'The Return of [X]',
  'I Brought Back [X]',
  'Saving [X] From Cancellation',
  'Apologizing to [X] After All These Years',
  'My Honest Reaction to [X]',
  'Opening My First [X] in Years',
  'Unboxing My [X] Package',
  'Mystery Box Full of [X]',
  'Ordering [X] Off the Dark Web',
  'Every [X] Ranked Worst to Best',
  'What Happens If You [X] for 30 Days?',
  'POV: You\'re [X] and Everything Is on Fire'
];

function pickRandomFormats(n = 6) {
  const shuffled = [...FORMATS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}

module.exports = { FORMATS, pickRandomFormats };
