const PERSONAS = [
  // Big YouTube creators
  'MrBeast',
  'Ryan Trahan',
  'Mark Rober',
  'Emma Chamberlain',
  'Ali Abdaal',
  'Casey Neistat',
  'PewDiePie',
  'Dream',
  'Logan Paul',
  'Jake Paul',
  'KSI',
  'Sidemen',
  'Airrack',
  'Michelle Khare',
  'Matt Rife',
  'Brent Rivera',
  'Zach King',
  'David Dobrik',
  'iShowSpeed',
  'Kai Cenat',
  'Tyler1',
  'Pokimane',
  'Valkyrae',
  'Ludwig',
  'Jacksepticeye',
  'Markiplier',
  'TommyInnit',
  'Technoblade',
  'Dude Perfect',
  'Smosh',
  'Liza Koshy',
  'Colleen Ballinger',
  'Jenna Marbles',
  'Shane Dawson',
  'James Charles',
  'NikkieTutorials',
  'Safiya Nygaard',
  'Michelle Phan',
  'Bon Appétit',
  'Binging with Babish',
  'Joshua Weissman',
  'Matty Matheson',
  'Ethan Chlebowski',
  'Adam Ragusea',
  'How To Basic',
  'Veritasium',
  'Vsauce',
  'Kurzgesagt',
  'CGP Grey',
  'Tom Scott',
  'Marques Brownlee',
  'Linus Tech Tips',
  'iJustine',
  'Unbox Therapy',
  'The Try Guys',
  'Good Mythical Morning',
  'Rhett and Link',
  'Vat19',
  'Blippi',
  'Cocomelon',
  'Ryan\'s World',
  'Like Nastya',

  // Celebrities / characters
  'Gordon Ramsay',
  'The Rock',
  'Elon Musk',
  'Taylor Swift',
  'Kim Kardashian',
  'Drake',
  'Keanu Reeves',
  'Morgan Freeman',
  'Snoop Dogg',
  'Joe Rogan',
  'Oprah',
  'Martha Stewart',
  'Bob Ross',
  'David Attenborough',
  'Ronaldo',
  'Messi',
  'LeBron James',
  'Serena Williams',

  // Mythic / fictional
  'Santa Claus',
  'God',
  'The Devil',
  'Grim Reaper',
  'Jesus',
  'Zeus',
  'Medusa',
  'A Medieval King',
  'A Viking Warrior',
  'A Billionaire',
  'A Toddler',
  'A Vampire',
  'A Werewolf',
  'A Time Traveler',
  'A Failed Magician',
  'A Fitness Influencer',
  'A Cult Leader',
  'A Tech Bro',
  'A Pirate',
  'A Dragon',
  'A Sad Clown',
  'A Conspiracy Theorist',
  'A YouTube Guru',
  'A Flat Earther',
  'A Robot',
  'A Ghost',
  'A Zombie',
  'A Wizard',
  'A Dungeon Master',
  'A Knight',
  'A Samurai',
  'A Ninja',
  'A Cowboy',
  'An Alien',
  'A Cavewoman',
  'A Roman Emperor',
  'A Villain',
  'A Superhero',
  'A Bodybuilder',
  'A Yoga Instructor',
  'A Motivational Speaker',
  'A Life Coach',
  'A Used Car Salesman',
  'A Crypto Bro',
  'A Hedge Fund Manager',
  'A Reality TV Contestant',
  'An Influencer',
  'A Karen',
  'A Boomer',
  'A Gen Z Intern',
  'A Finance TikToker',
  'A Retired Wrestler',
  'A Retired Spy',
  'A Failed Astronaut',
  'A Tired Barista',
  'A Competitive Eater',
  'A Hot Dog Vendor',
  'A Mall Cop',
  'A Taxi Driver',
  'A Substitute Teacher',
  'A Divorce Lawyer',
  'A Dentist With A Grudge',
  'A Haunted Doll',
  'A Possessed Roomba',
  'A Talking Dog',
  'A Sentient Air Fryer',

  // Personal life
  'Your Mom',
  'Your Dad',
  'Your Grandma',
  'Your Wife',
  'Your Husband',
  'Your Boss',
  'Your Ex',
  'Your Therapist',
  'Your Neighbor',
  'Your Landlord',
  'Your Best Friend',
  'Your Childhood Bully',
  'Your High School Crush'
];

function pickRandomPersonas(n = 5) {
  const shuffled = [...PERSONAS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}

module.exports = { PERSONAS, pickRandomPersonas };
